[tool.poetry]
name = "oceandata"
version = "0.2.3"
description = ""
authors = ["Bror Jonsson <brorfred@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = ">0.25"
numpy = "^1.16"
requests = "^2.21"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
